# Generated by Django 3.1 on 2020-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(default='', max_length=50)),
                ('r_phone', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('sim', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('plan', models.CharField(default='', max_length=50)),
                ('validity', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
