# Generated by Django 3.1 on 2020-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='month9',
            field=models.BooleanField(default=False),
        ),
    ]
