# Generated by Django 3.1 on 2020-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20200906_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='2020-09-06'),
        ),
    ]
