# Generated by Django 3.1 on 2020-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_auto_20200908_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default='0', max_length=12),
        ),
    ]
