# Generated by Django 3.1 on 2020-09-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0009_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
