# Generated by Django 3.1 on 2020-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_auto_20200911_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
