# Generated by Django 3.1 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0012_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='t_status',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='t_token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
